### PR TITLE
Use default solver tolerances in TALA DG

### PR DESCRIPTION
**Pull request by Patol75**
Fixing what I believe was forgotten in gh-124. Let us see what the CI returns.

### CODE REVIEW

**Comment by angus-g** [comment]
This will likely fail. The part of the comment you missed was that it requires an adjustment to the testing tolerances.

**Comment by drhodrid** [comment]
There has been some confusion here, probably due to poor communication on my side. The results that are currently being tested against used default tolerances for everything. It took over an hour on 16 cores on Erebus. What we need is to leave this on 16 cores (@angus-g and I have already agreed to this), but remove the additional rtol line. I have just done this - so assuming it goes green this can be merged.

**Comment by Patol75** [comment]
The idea is that you could keep `stokes_solver.solver_parameters['snes_rtol'] = 1e-2` (anyone knows what the default value is?) and run on 16 cores if you wanted to retain a reasonable run time. That would not affect CI results, as demonstrated above (this specific case took 1 hour and 40 minutes on 4 cores).

**Comment by drhodrid** [comment]
That line is not needed in this example, hence why I’ve removed it.

On 4 Nov 2024, at 1:52 pm, Thomas Duvernay ***@***.***> wrote:



The idea is that you could keep stokes_solver.solver_parameters['snes_rtol'] = 1e-2 (anyone knows what the default value is?) and run on 16 cores if you wanted to retain a reasonable run time. That would not affect CI results, as demonstrated above (this specific case took 1 hour and 40 minutes on 4 cores).

**Comment by Patol75** [comment]
CI is green, the test passed in ~40 minutes.

**Review by drhodrid — APPROVED** [review]
Thanks @Patol75! 40 mins on 16 cores is good! Go go go!

**Pull request merged**
