### PR TITLE
Introduce Truncated Anelastic Liquid Approximation Option

### PR DESCRIPTION
**Pull request by drhodrid**
Modify approximations slightly to include TALA functionality. This is done by TALA inheriting the EBA class (with required additions) and, subsequently, ALA inheriting the TALA class (with required additions). I have added a test case. For @angus-g information and for consistency: I changed our compressible test to compressible_ALA, and called new one compressible_TALA, for ease of differentiation. For the CI, final line of params.log looks like this - are you able to use this for expected values?

`6038 0.5935141415782041 9.794718323638744e-05 9.987549797948552e-10 156.29190781258126 178.23475831858875 231.72964363219035 7.912896098516475 7.795333393185675 0.11756270533079949 0.5455414058198512 3.2472586509667534 3.2764495261239452 0.029190875157191876`

### CODE REVIEW

**Review by stephankramer — CHANGES_REQUESTED** [review]
Looks good (if I may say so myself). Pushed a further little simplification.

I think you need to update the test_all script and update the expected.pkl (which should hopefully be different than the ALA one!)

**Comment by angus-g** [comment]
Expected values updated. For future reference (and I'll write this up somewhere less ephemeral than a PR comment), once you've added the case to `test_all.py`, you can run `python3 generate_expected.py 2d_compressible_TALA`

**Comment by angus-g** [comment]
CI failure because the result on the Runner on Kerguelen has a pretty different convergence to the one in the original message. Last line of `params.log` is:
```
7597 0.5766542572093242 7.509406051733994e-05 9.997308424626185e-10 156.29197994864927 178.23483844544072 231.72971340970327 7.912901082838214 7.795334749140693 0.11756633369752123 0.5455412471405021 3.2472599126369923 3.2764508202750298 0.029190907638037444
```
Which is a good 1500 timesteps more!

**Comment by drhodrid** [comment]
Ahhh blooming heck! I’ll look into this Monday! Sorry - perhaps I got the wrong run!


----------------------------------------------------------------------------------------------------------
Professor (Computational & Observational Geodynamics)
Associate Director Research & Engagement
Research School of Earth Sciences,
The Australian National University,
Mills Road, Acton,
Canberra, ACT, 2601, Australia

T: +61 (0)2 6125 3643
E: ***@***.***
W: https://earthsciences.anu.edu.au/people/academics/professor-rhodri-davies
CRICOS Provider No. 00120C
----------------------------------------------------------------------------------------------------------

On 9 Sep 2023, at 8:32 pm, Angus Gibson ***@***.***> wrote:



CI failure because the result on the Runner on Kerguelen has a pretty different convergence to the one in the original message. Last line of params.log is:

7597 0.5766542572093242 7.509406051733994e-05 9.997308424626185e-10 156.29197994864927 178.23483844544072 231.72971340970327 7.912901082838214 7.795334749140693 0.11756633369752123 0.5455412471405021 3.2472599126369923 3.2764508202750298 0.029190907638037444


Which is a good 1500 timesteps more!

**Pull request merged**
