### PR TITLE
Update to reflect recent Firedrake changes

### PR DESCRIPTION
**Pull request by angus-g**
This was going to be a simple single commit, but there are multiple issues stemming from the recent Firedrake updates. At least they'll be documented as we work through them. The `atan_2 -> atan2` fix is simple, but it's now showing up that the `rol_solver.py` implementation in pyadjoint doesn't conform to the new `Cofunction` interface in Firedrake. Instead of taking the result of `rf.derivative()` and passing that through the Riesz map, we should just pass the `riesz_representation` option through the derivative in the first place.

I'll submit a PR to pyadjoint, and pin the CI to a working branch as a temporary measure.

### CODE REVIEW

**Comment by angus-g** [comment]
It's not being caught in the Actions log, but the new failure is _again_ `atan2`-related:
```
Traceback (most recent call last):
  File "/home/firedrake/g-adopt/demos/analytical_comparisons/analytical.py", line 148, in <module>
    args.func(args)
  File "/home/firedrake/g-adopt/demos/analytical_comparisons/analytical.py", line 90, in run_subcommand
    errors = model(*args.params)
  File "/home/firedrake/g-adopt/demos/analytical_comparisons/smooth_cylindrical_freeslip.py", line 84, in model
    stokes_solver.solve()
  File "/home/firedrake/g-adopt/gadopt/stokes_integrators.py", line 179, in solve
    self.setup_solver()
  File "/home/firedrake/g-adopt/gadopt/stokes_integrators.py", line 168, in setup_solver
    self.problem = fd.NonlinearVariationalProblem(self.F, self.solution,
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/lib/python3.10/site-packages/pyadjoint/tape.py", line 105, in wrapper
    return function(*args, **kwargs)
  File "/home/firedrake/firedrake/src/firedrake/firedrake/adjoint_utils/variational_solver.py", line 26, in wrapper
    self._ad_adj_F = adjoint(dFdu)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/ufl_expr.py", line 336, in adjoint
    return ufl.adjoint(form, reordered_arguments)
  File "/home/firedrake/firedrake/src/ufl/ufl/formoperators.py", line 166, in adjoint
    form = expand_derivatives(form)
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/ad.py", line 34, in expand_derivatives
    form = apply_derivatives(form)
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/apply_derivatives.py", line 1468, in apply_derivatives
    dexpression_dvar = map_integrand_dags(rules, expression)
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 73, in map_integrand_dags
    return map_integrands(lambda expr: map_expr_dag(function, expr, compress),
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 25, in map_integrands
    mapped_integrals = [map_integrands(function, itg, only_integral_type)
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 25, in <listcomp>
    mapped_integrals = [map_integrands(function, itg, only_integral_type)
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 33, in map_integrands
    return itg.reconstruct(function(itg.integrand()))
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/map_integrands.py", line 73, in <lambda>
    return map_integrands(lambda expr: map_expr_dag(function, expr, compress),
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 34, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 100, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/apply_derivatives.py", line 1309, in coefficient_derivative
    mapped_expr = map_expr_dag(rules, f,
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 34, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 98, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/home/firedrake/firedrake/src/ufl/ufl/algorithms/apply_derivatives.py", line 60, in expr
    raise ValueError(f"Missing differentiation handler for type {o._ufl_class_.__name__}. "
ValueError: Missing differentiation handler for type Atan2. Have you added a new type?
```

**Comment by angus-g** [comment]
Looks like this is because of:
```
>>> from ufl.utils.formatting import camel2underscore
>>> camel2underscore("Atan2")
'atan_2'
```

Will post an issue/PR...

**Comment by angus-g** [comment]
UFL changes all merged at least! Will try to upstream the pyadjoint fixes, but at least they're working in my branch.

**Comment by angus-g** [comment]
@stephankramer should we merge this first so at least the CI is fixed for the other PRs? And then we can rebase them and handle them all in turn.

**Review by stephankramer — APPROVED** [review]
Yes, please do merge first. This all looks good

**Pull request merged**
