### PR TITLE
Make sure long free surface test runs

### LINKED ISSUE #118: Long free surface test doesn't run
I forgot to run smooth_cylindrical_freesurface.py in the long test suite for a while so the runscript can't run on the new
master branch. 

Needs mesh.cartesian and not use solution_old from stokes integrators

### PR DESCRIPTION
**Pull request by w3168**
Fixes #118

### CODE REVIEW

**Comment by w3168** [comment]
I've set off a long test from this branch so will see what happens

**Comment by angus-g** [comment]
Because we have some unit tests that import firedrake, I'll need to tweak how the pytest report is generated. I ran it manually and got a failure on `test_analytical[smooth/cylindrical/free_surface-convergence(4.0, 2.0, 2.0)-rtol0.1-k8-n4]`:
```
E               FileNotFoundError: [Errno 2] No such file or directory: .../g-adopt/tests/analytical_comparisons/errors-smooth_cylindrical_free_surface-levels4-k8-n4.dat
```

There was also the Level 5 parallel scaling failure (about 300s too slow)

**Comment by w3168** [comment]
hmm ok looks like there was a similiar issue previously that I thought was resolved by changing the number of cores...
https://github.com/g-adopt/g-adopt/pull/51/commits/9e38b61e0e729fc37b34658e9b9904a855ae7d5c

**Comment by angus-g** [comment]
I think that's a good theory. Level 4 runs on 16 cores, but even on 8 cores I get a diverged solve with k=8, n=4. It seems to work (more slowly) for 4 cores, however.

**Comment by Patol75** [comment]
When I ran `smooth/cylindrical/free_surface` on the `update_approx` branch yesterday, I also ran into a `DIVERGED_LINEAR_SOLVE` error for `level=4`, `k=8`, `n=4`. I was using 4 processes.

**Comment by w3168** [comment]
ah ok... @angus-g reckoned that 4 cores was running ok on gadi but I guess we'll see after the long test finishes

**Comment by w3168** [comment]
@Patol75 @angus-g looks like it worked ok :) 
https://github.com/g-adopt/g-adopt/actions/runs/11156390899

**Review by angus-g — APPROVED** [review]
Great!

**Pull request merged**
